name: Desplegar en Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Instalar dependencias y construir
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Generar artifact (opcional)
        run: zip -r release.zip ./*
      
      - name: Subir artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
    permissions:
      contents: read
    steps:
      - name: Descargar artifact (opcional)
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Desempaquetar artifact (opcional)
        run: unzip release.zip
      
      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Desplegar en Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}      # Asegúrate de que es el Project Token correcto
          RAILWAY_PROJECT: ${{ secrets.RAILWAY_PROJECT }}      # El ID o nombre del proyecto
          RAILWAY_SERVICE: "AlphaTraderServer"                # El nombre del servicio a desplegar
        run: |
          # Desplegar solamente el servicio deseado
          railway up --service "$RAILWAY_SERVICE"
